# Generated by Django 4.1 on 2022-10-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletica',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
