# Generated by Django 4.1 on 2022-10-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
        ('atletica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='competicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campanha.competicao'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='atletica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atletica.atletica'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField()),
                ('atletica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atletica.atletica')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanha.campanha')),
            ],
        ),
    ]
