# Generated by Django 4.1 on 2022-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='naipe',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Naipe'),
        ),
    ]
