# Generated by Django 4.1 on 2022-08-23 17:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('data_incio', models.DateField(default=datetime.date.today, verbose_name='Data de início')),
                ('data_final', models.DateField(default=datetime.date.today, verbose_name='Data de término')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do evento')),
                ('status', models.CharField(choices=[(1, 'ativo'), (0, 'inativo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LigaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_liga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
