# Generated by Django 4.1 on 2022-09-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='data_incio',
            new_name='data_inicio',
        ),
    ]
