# Generated by Django 4.1 on 2022-09-20 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0002_alter_modalidade_options'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanha',
            options={'verbose_name': 'campanha', 'verbose_name_plural': 'campanhas'},
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[(1, 'ativo'), (0, 'inativo')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data da competição')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.campanha')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modalidade.modalidade')),
            ],
            options={
                'verbose_name': 'competicao',
                'verbose_name_plural': 'competicoes',
            },
        ),
    ]
