# Generated by Django 4.1 on 2022-10-21 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletica', '0002_initial'),
        ('campanha', '0002_alter_competicao_campanha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='campanha.competicao')),
                ('equipe1', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Primeiro_Lugar', to='atletica.equipe')),
                ('equipe2', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Segundo_Lugar', to='atletica.equipe')),
                ('equipe3', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Terceiro_Lugar', to='atletica.equipe')),
                ('equipe4', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Quarto_Lugar', to='atletica.equipe')),
                ('equipe5', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Quinto_Lugar', to='atletica.equipe')),
                ('equipe6', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sexto_Lugar', to='atletica.equipe')),
                ('equipe7', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Setimo_Lugar', to='atletica.equipe')),
                ('equipe8', models.ForeignKey(default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Oitavo_Lugar', to='atletica.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequencia do jogo')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data de início')),
                ('etapa', models.CharField(choices=[('P', 'Pre-liminar'), ('O', 'Oitavas'), ('Q', 'Quartas'), ('S', 'Semi-final'), ('T', 'Terceiro lugar'), ('F', 'Final')], default='P', max_length=1, null=True, verbose_name='Etapa')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanha.competicao')),
                ('equipe_vencedora', models.ForeignKey(blank=True, default='A definir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Equipe_vencedora', to='atletica.equipe')),
                ('equipes', models.ManyToManyField(blank=True, related_name='Equipes_partida', to='atletica.equipe')),
            ],
        ),
    ]
