# Generated by Django 4.1 on 2022-10-19 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletica', '0003_equipe_competicao_alter_atleta_status_and_more'),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data de início')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanha.competicao')),
                ('equipe', models.ManyToManyField(to='atletica.equipe')),
            ],
        ),
    ]
