# Generated by Django 4.1 on 2022-10-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_alter_campanha_status'),
        ('atletica', '0004_alter_score_options_atletica_logo'),
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='equipe_vencedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Equipe_vencedora', to='atletica.equipe'),
        ),
        migrations.AddField(
            model_name='partida',
            name='equipes',
            field=models.ManyToManyField(related_name='Equipes_partida', to='atletica.equipe'),
        ),
        migrations.AddField(
            model_name='partida',
            name='etapa',
            field=models.CharField(choices=[('P', 'Pre-liminar'), ('O', 'Oitavas'), ('Q', 'Quartas'), ('S', 'Semi-final'), ('T', 'Terceiro lugar'), ('F', 'Final')], default='P', max_length=1, null=True, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campanha.competicao')),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Primeiro_Lugar', to='atletica.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Segundo_Lugar', to='atletica.equipe')),
                ('equipe3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Terceiro_Lugar', to='atletica.equipe')),
                ('equipe4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Quarto_Lugar', to='atletica.equipe')),
                ('equipe5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Quinto_Lugar', to='atletica.equipe')),
                ('equipe6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sexto_Lugar', to='atletica.equipe')),
                ('equipe7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Setimo_Lugar', to='atletica.equipe')),
                ('equipe8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Oitavo_Lugar', to='atletica.equipe')),
            ],
        ),
    ]
