# Generated by Django 4.1 on 2022-10-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletica', '0002_initial'),
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='equipe',
        ),
        migrations.AlterField(
            model_name='partida',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='Equipes_partida', to='atletica.equipe'),
        ),
    ]
