# Generated by Django 4.1 on 2022-10-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='md',
            field=models.CharField(choices=[(1, 'Um'), (3, 'Tres'), (5, 'Cinco')], default=1, max_length=1, verbose_name='Melhor de:'),
        ),
    ]
