# Generated by Django 4.1 on 2022-10-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_partida_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competidor',
            old_name='resultado',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='competidor',
            name='unidade',
        ),
        migrations.AddField(
            model_name='partida',
            name='unidade',
            field=models.CharField(choices=[('P', 'Pontos'), ('S', 'Sets'), ('G', 'Gols'), ('T', 'Segundos'), ('M', 'Minutos'), ('R', 'Rodadas'), ('O', 'Geral')], default='O', max_length=1, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='etapa',
            field=models.CharField(choices=[('P', 'Pre-liminar'), ('O', 'Oitavas'), ('Q', 'Quartas'), ('D', 'Quartas-desempate | Quinto e Sexto'), ('U', 'Quartas-desempate | Setimo e Oitavo'), ('S', 'Semi-final'), ('T', 'Terceiro lugar'), ('F', 'Final')], default='P', max_length=1, null=True, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='md',
            field=models.CharField(choices=[(1, 'Um (1)'), (3, 'Tres (3)'), (5, 'Cinco (5)')], default=1, max_length=1, verbose_name='Melhor de:'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.PositiveIntegerField()),
                ('md', models.PositiveIntegerField(default=1)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.competidor')),
            ],
        ),
    ]
