# Generated by Django 4.1 on 2022-10-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_rename_resultado_competidor_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Pontuacao do jogo:')),
                ('md', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='competidor',
            old_name='valor',
            new_name='resultado',
        ),
        migrations.AlterField(
            model_name='partida',
            name='md',
            field=models.CharField(choices=[('1', 'Um (1)'), ('3', 'Tres (3)'), ('5', 'Cinco (5)')], default=1, max_length=1, verbose_name='Melhor de:'),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='competidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.competidor'),
        ),
    ]
