# Generated by Django 4.1 on 2022-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('tipo', models.CharField(choices=[('C', 'Coletiva'), ('I', 'Individual'), ('V', 'Virtual'), ('M', 'Mesa')], max_length=1)),
                ('max_atletas', models.PositiveIntegerField()),
                ('min_atletas', models.PositiveIntegerField()),
                ('naipe', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Misto')], max_length=1)),
                ('tipo_confronto', models.CharField(choices=[('0', 'Mata-mata'), ('1', 'Todos-x-todos')], max_length=1)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['nome'],
            },
        ),
    ]
