# Generated by Django 4.1 on 2022-10-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='eh_misto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='tipo_confronto',
            field=models.CharField(choices=[(0, 'Mata-mata'), (1, 'Todos-x-todos')], max_length=1),
        ),
    ]
