# Generated by Django 4.1 on 2022-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade', '0002_modalidade_eh_misto_alter_modalidade_tipo_confronto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='tipo_confronto',
            field=models.CharField(choices=[('0', 'Mata-mata'), ('1', 'Todos-x-todos')], max_length=1),
        ),
    ]
