# Generated by Django 4.1 on 2022-10-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[(1, 'ativo'), (0, 'inativo')], default=1, max_length=1),
        ),
    ]
